Added api config for V2 scoping handler.
hmrc/individuals-employments-api pull request #47
Opened 2020-11-13 15:10 UTC by parkeradam

2020-11-16 10:20 UTC, ajchilts approved these changes
LGTM 👍 Nice one.

2020-11-16 10:44 UTC, ajchilts requested changes

2020-11-16 10:44 UTC, ajchilts commented on conf/application.conf
> +    endpoints {
Also this endpoint config looks different to that in the test config used bu the code for testing the handler pattern. 

```
    endpoints = List(
      EndpointConfig(
        name = mockEndpoint1,
        link = "/a/b/c?matchId=<matchId>{&fromDate,toDate}",
        fields = Map(
          "A" -> "payments",
          "B" -> "employer/employerName=\"foo bar\"",
          "C" -> "employer/employerAddress/line1",
          "D" -> "employer/employerAddress/line2",
          "E" -> "employer/employerAddress/line3",
          "F" -> "employer/employerDistrictNumber",
          "G" -> "employer/employerSchemeReference",
          "H" -> "employmentStartDate",
          "I" -> "employmentLeavingDate",
          "J" -> "employmentPayFrequency",
          "K" -> "employeeAddress",
          "L" -> "payrollId"
        )
      ),
```

I think we will need to align to this name, link, fields 

Name is the string name of the endpoint used by the endpoint to fetch the scopes. 

Link is the full url for HAL 

Fields are the fields. 

@owen-opencast  can help confirm this?

2020-11-16 11:13 UTC, ajchilts requested changes

2020-11-16 11:13 UTC, ajchilts commented on conf/application.conf
> +            endpoint = "/individuals/employment/paye"
Update to correct HAL link and ensure endpoint keys match those in the controllers `getEndPointScopes` invocation.

2020-11-18 14:46 UTC, owen-opencast approved these changes

2020-11-18 16:42 UTC, ajchilts approved these changes

2020-11-18 16:42 UTC, merged