MDS-373 | Implemented v2 routes
hmrc/individuals-employments-api pull request #59
Opened 2020-12-09 16:37 UTC by owen-opencast

2020-12-17 11:12 UTC, parkeradam requested changes
Also as a general comment. I had an issue when trying to bring the project up to check tests locally that the typesafe URL in plugins.sbt wouldnt load as it is http instead of https. May be worth updating from 
resolvers += "Typesafe Releases" at "http://repo.typesafe.com/typesafe/releases/"
to
resolvers += "Typesafe Releases" at "https://repo.typesafe.com/typesafe/releases/"
as this allowed me to open the project.

2020-12-17 11:12 UTC, parkeradam commented on test/unit/uk/gov/hmrc/individualsemploymentsapi/domain/PayFrequencySpec.scala
> +import uk.gov.hmrc.individualsemploymentsapi.domain.v1.PayFrequency
Worth shifting to a V1 package in tests to match structure of application making it easier to find?

2020-12-17 14:55 UTC, parkeradam approved these changes

2020-12-18 15:53 UTC, ajchilts approved these changes
Well done 👍

2021-01-05 12:46 UTC, merged